#! /bin/bash

XZ="xz --compress --lzma2 --format=xz --check=crc64"
XZ86="xz --compress --x86 --lzma2 --format=xz --check=crc64"
MBSDIFF="./mbsdiff/mbsdiff"
ZUCCHINI="./zucchini/zucchini -gen"

function do_extract() {
  PLATFORM=$1
  VERSION=$2

  DIR=extracts/$PLATFORM/$VERSION
  echo $DIR

  if [ -d $DIR ]; then
    return
  fi

  ./extract $PLATFORM $VERSION
}

function get_sizes() {
  TYPE=$1
  FILE=$2
  LAST=$3

  echo -e "        \"$TYPE\": { \n\
          \"xzsize\": $($XZ --stdout $FILE | wc -c), \n\
          \"xz86size\": $($XZ86 --stdout $FILE | wc -c), \n\
          \"size\": $(cat $FILE | wc -c)" >> $TARGET

  if [ $LAST -eq 1 ]; then
    echo -e "        }" >> $TARGET
  else
    echo -e "        }," >> $TARGET
  fi
}

INFO="/dev/stdout"
NOISY="/dev/stdout"
PLATFORM=""

while [ "$PLATFORM" == "" ]; do
  case $1 in
    -q )  NOISY="/dev/null"
          ;;
    -s )  NOISY="/dev/null"
          INFO="/dev/null"
          ;;
    * )   PLATFORM=$1
          ;;
  esac
  shift
done

OLDVERSION=$1
NEWVERSION=$2
TARGET="results/$PLATFORM-$OLDVERSION-$NEWVERSION.json"

if [ -f "$TARGET" ]; then
  exit
fi

TYPE=`./update_type $OLDVERSION $NEWVERSION`

OLDDIR=`do_extract $PLATFORM $OLDVERSION`
NEWDIR=`do_extract $PLATFORM $NEWVERSION`

FIRST=0

echo "Building data for ${PLATFORM} ${OLDVERSION} ${NEWVERSION}" > $INFO

echo -e "{ \n\
  \"type\": \"$TYPE\", \n\
  \"oldVersion\": \"$OLDVERSION\", \n\
  \"newVersion\": \"$NEWVERSION\", \n\
  \"platform\": \"$PLATFORM\", \n\
  \"files\": [" >$TARGET
for new_file in `cd $NEWDIR && find -type f`
do
  path=`echo "$new_file" | cut -c3-`
  if ! test -f "$OLDDIR/$path" || ! diff -q $OLDDIR/$path $NEWDIR/$path >/dev/null; then
    echo $path > $NOISY
    if [ $FIRST -eq 0 ]; then
      FIRST=1
    else
      echo "    }," >> $TARGET
    fi

    filename=`basename -- "$path"`
    extension="${filename##*.}"

    echo -e "    { \n\
      \"path\": \"$path\", \n\
      \"type\": \"$extension\", \n\
      \"sizes\": {" >> $TARGET

    if [ -f "$OLDDIR/$path" ]; then
      PATCH=`mktemp`
      echo "  zucchini..." > $NOISY
      $ZUCCHINI "$OLDDIR/$path" "$NEWDIR/$path" "$PATCH" > /dev/null 2> /dev/null
      get_sizes zucchini $PATCH 0
      rm $PATCH

      echo "  mbsdiff..." > $NOISY
      $MBSDIFF "$OLDDIR/$path" "$NEWDIR/$path" "$PATCH" > /dev/null
      get_sizes mbsdiff $PATCH 0
      rm $PATCH
    fi

    get_sizes original $NEWDIR/$path 1
    echo -e "      }" >> $TARGET
  fi
done
echo -e "    } \n\
  ] \n\
}" >> $TARGET
