#! /bin/bash

VERSION=$1
rm -rf releases/${VERSION}
mkdir -p releases/${VERSION}/win64
mkdir -p releases/${VERSION}/win32
mkdir -p releases/${VERSION}/linux-x86_64
mkdir -p releases/${VERSION}/linux-i686
mkdir -p releases/${VERSION}/mac
curl --parallel \
  "http://ftp.mozilla.org/pub/firefox/releases/${VERSION}/win64/en-US/Firefox%20Setup%20${VERSION}.exe" -o "releases/${VERSION}/win64/firefox.exe" \
  "http://ftp.mozilla.org/pub/firefox/releases/${VERSION}/win32/en-US/Firefox%20Setup%20${VERSION}.exe" -o "releases/${VERSION}/win32/firefox.exe" \
  "http://ftp.mozilla.org/pub/firefox/releases/${VERSION}/linux-x86_64/en-US/firefox-${VERSION}.tar.bz2" -o "releases/${VERSION}/linux-x86_64/firefox.tar.bz2" \
  "http://ftp.mozilla.org/pub/firefox/releases/${VERSION}/linux-i686/en-US/firefox-${VERSION}.tar.bz2" -o "releases/${VERSION}/linux-i686/firefox.tar.bz2" \
  "http://ftp.mozilla.org/pub/firefox/releases/${VERSION}/mac/en-US/Firefox%20${VERSION}.dmg" -o "releases/${VERSION}/mac/firefox.dmg"
