#! /bin/bash

PLATFORM="$1"
VERSION="$2"

for file in `ls updates/${VERSION}/${PLATFORM}`
do
  OLDVERSION=`echo ${file} | cut -d'-' -f 2`
  if [ -d "releases/$OLDVERSION/$PLATFORM" ]; then
    echo $OLDVERSION
  fi
done
